/* 
 * Gitea API.
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.1.1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using OpenAPIDateConverter = Gitea.Client.OpenAPIDateConverter;

namespace Gitea.Model
{
    /// <summary>
    /// ExternalWiki represents setting for external wiki
    /// </summary>
    [DataContract]
    public partial class ExternalWiki :  IEquatable<ExternalWiki>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ExternalWiki" /> class.
        /// </summary>
        /// <param name="externalWikiUrl">URL of external wiki..</param>
        public ExternalWiki(string externalWikiUrl = default(string))
        {
            this.ExternalWikiUrl = externalWikiUrl;
        }
        
        /// <summary>
        /// URL of external wiki.
        /// </summary>
        /// <value>URL of external wiki.</value>
        [DataMember(Name="external_wiki_url", EmitDefaultValue=false)]
        public string ExternalWikiUrl { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ExternalWiki {\n");
            sb.Append("  ExternalWikiUrl: ").Append(ExternalWikiUrl).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ExternalWiki);
        }

        /// <summary>
        /// Returns true if ExternalWiki instances are equal
        /// </summary>
        /// <param name="input">Instance of ExternalWiki to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ExternalWiki input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ExternalWikiUrl == input.ExternalWikiUrl ||
                    (this.ExternalWikiUrl != null &&
                    this.ExternalWikiUrl.Equals(input.ExternalWikiUrl))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ExternalWikiUrl != null)
                    hashCode = hashCode * 59 + this.ExternalWikiUrl.GetHashCode();
                return hashCode;
            }
        }
    }

}
