/* 
 * Gitea API.
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.1.1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using OpenAPIDateConverter = Gitea.Client.OpenAPIDateConverter;

namespace Gitea.Model
{
    /// <summary>
    /// NotificationCount number of unread notifications
    /// </summary>
    [DataContract]
    public partial class NotificationCount :  IEquatable<NotificationCount>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="NotificationCount" /> class.
        /// </summary>
        /// <param name="_new">_new.</param>
        public NotificationCount(long _new = default(long))
        {
            this.New = _new;
        }
        
        /// <summary>
        /// Gets or Sets New
        /// </summary>
        [DataMember(Name="new", EmitDefaultValue=false)]
        public long New { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class NotificationCount {\n");
            sb.Append("  New: ").Append(New).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as NotificationCount);
        }

        /// <summary>
        /// Returns true if NotificationCount instances are equal
        /// </summary>
        /// <param name="input">Instance of NotificationCount to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(NotificationCount input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.New == input.New ||
                    (this.New != null &&
                    this.New.Equals(input.New))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.New != null)
                    hashCode = hashCode * 59 + this.New.GetHashCode();
                return hashCode;
            }
        }
    }

}
