/* 
 * Gitea API.
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.1.1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using OpenAPIDateConverter = Gitea.Client.OpenAPIDateConverter;

namespace Gitea.Model
{
    /// <summary>
    /// StopWatch represent a running stopwatch
    /// </summary>
    [DataContract]
    public partial class StopWatch :  IEquatable<StopWatch>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="StopWatch" /> class.
        /// </summary>
        /// <param name="created">created.</param>
        /// <param name="issueIndex">issueIndex.</param>
        public StopWatch(DateTime created = default(DateTime), long issueIndex = default(long))
        {
            this.Created = created;
            this.IssueIndex = issueIndex;
        }
        
        /// <summary>
        /// Gets or Sets Created
        /// </summary>
        [DataMember(Name="created", EmitDefaultValue=false)]
        public DateTime Created { get; set; }

        /// <summary>
        /// Gets or Sets IssueIndex
        /// </summary>
        [DataMember(Name="issue_index", EmitDefaultValue=false)]
        public long IssueIndex { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class StopWatch {\n");
            sb.Append("  Created: ").Append(Created).Append("\n");
            sb.Append("  IssueIndex: ").Append(IssueIndex).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as StopWatch);
        }

        /// <summary>
        /// Returns true if StopWatch instances are equal
        /// </summary>
        /// <param name="input">Instance of StopWatch to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(StopWatch input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Created == input.Created ||
                    (this.Created != null &&
                    this.Created.Equals(input.Created))
                ) && 
                (
                    this.IssueIndex == input.IssueIndex ||
                    (this.IssueIndex != null &&
                    this.IssueIndex.Equals(input.IssueIndex))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Created != null)
                    hashCode = hashCode * 59 + this.Created.GetHashCode();
                if (this.IssueIndex != null)
                    hashCode = hashCode * 59 + this.IssueIndex.GetHashCode();
                return hashCode;
            }
        }
    }

}
